### ISSUE TITLE
scene graph data for coco test online server 

### ISSUE THREAD

**Issue by Archer-Fang** [ltguo19/VSUA-Captioning#7]
hello,thanks for you work,i can not find image scene graph for test serve,would you mind providing it? I refer to SAGE ,however,i find this issue https://github.com/yangxuntu/SGAE/issues/18 which means image scene graph for test serve is not right

**Comment by ltguo19** [comment]
I checked the data in `coco_pred_sg_test.npy` and found that the data is correct but the dictionary is mismatching. The relation label in  `coco_pred_sg_test.npy` starts from 0, while the relation dictionary in `coco_pred_sg_rela.npy` starts from 408. 
Therefore, in order to get the correct relation labels, you should add `408` to the relation label in  `coco_pred_sg_test.npy` .
